"use client";
import { useState,useEffect,useRef } from "react";
import { defaults,fields,type Settings,type Field,type ManualRule } from "@/lib/settings";
import type { Analysis } from "@/lib/types";
import SettingsForm from "./SettingsForm";
const labels:Record<Field,string>={title:"Titre",url:"Lien",publishedAt:"Date",description:"Description",image:"Image",author:"Auteur",category:"Catégorie"};
const blank:ManualRule={type:"css",container:"article",fields:{title:{selector:"h2",mode:"text"},url:{selector:"a",mode:"url",attribute:"href"},publishedAt:{selector:"time",mode:"attribute",attribute:"datetime"},description:{selector:"p",mode:"text"},image:{selector:"img",mode:"url",attribute:"src"}}};
export function ArticlePreview({analysis}:{analysis:Analysis}) {return <><p>Nombre total détecté : {analysis.items.length} · Confiance : {analysis.settings?.manual?"utilisateur":`${Math.round(analysis.confidence*100)} %`} · {analysis.method.toUpperCase()}</p><div className="table-scroll"><table><thead><tr><th>Titre</th><th>Date</th><th>URL</th><th>Description</th><th>Image</th></tr></thead><tbody>{analysis.items.slice(0,10).map(i=><tr key={i.url}><td>{i.title}</td><td title={i.originalDate}>{i.publishedAt?new Date(i.publishedAt).toLocaleString("fr-FR"):"—"}</td><td><a href={i.url} target="_blank" rel="noreferrer">{i.url}</a></td><td>{i.description}</td><td>{i.image?<a href={i.image} target="_blank" rel="noreferrer">Voir l’image</a>:"—"}</td></tr>)}</tbody></table></div></>;}
export default function ExtractionEditor({feed,initial}:{feed?:Analysis;initial?:Settings}) {
  const [url,setUrl]=useState(feed?.url ?? "");const [title,setTitle]=useState(feed?.title ?? "");const [config,setConfig]=useState<Settings>(initial ?? defaults);
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [token,setToken]=useState("");const [html,setHtml]=useState("");const [analysis,setAnalysis]=useState<Analysis>();const [matches,setMatches]=useState<Record<string,{count:number;values:string[]}>>({});const [total,setTotal]=useState<number>();const [pick,setPick]=useState<Field>("title");const iframe=useRef<HTMLIFrameElement>(null);const current=useRef({config,pick});current.current={config,pick};
  async function api(action:string,extra:Record<string,unknown>={}) {const response=await fetch("/api/editor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,url,settings:config,token,...extra})});const data=await response.json();if(!response.ok)throw new Error(`${data.code ?? ""} — ${data.message}`);return data;}
  useEffect(()=>{if(!token || !config.manual || config.manual.type!=="css")return;const controller=new AbortController();const timer=setTimeout(()=>{void fetch("/api/editor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"selectors",token,settings:config}),signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);setMatches(d.matches);setTotal(d.total);}).catch(e=>{if(!controller.signal.aborted){setMatches({});setTotal(undefined);setMessage(e.message);}});},400);return()=>{clearTimeout(timer);controller.abort();};},[token,config]);
  async function run(action:"preview"|"test") {setBusy(true);setMessage("");try{const data=await api(action);if(data.token){setToken(data.token);setHtml(data.html);}setAnalysis(data.analysis);setMessage(data.events?.map((e:{message:string})=>e.message).join("\n") ?? "");}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  async function save(){setBusy(true);try{if(feed){const r=await fetch(`/api/manage/${feed.id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"save",title,settings:config})});const d=await r.json();if(!r.ok)throw new Error(d.message);location.href=`/feeds/${feed.id}`;}else{if(!analysis)throw new Error("Testez les règles avant de créer le flux.");const r=await fetch("/api/feeds",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:analysis.id})});const d=await r.json();if(!r.ok)throw new Error(d.message);location.href=`/feeds/${analysis.id}`;}}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  const change=(s:Settings)=>{setConfig(s);setAnalysis(undefined);};
  const changeRule=(rule:ManualRule)=>change({...config,manual:rule});
  function connectPicker(){const doc=iframe.current?.contentDocument;if(!doc)return;doc.addEventListener("click",e=>{e.preventDefault();const target=e.target as Element;if(!target?.tagName)return;const {config:cfg,pick:field}=current.current;
    const selector=(el:Element)=>{const cls=[...el.classList].filter(c=>/^[a-zA-Z_][\w-]{1,60}$/.test(c)&&!/[a-f0-9]{10}|\d{5}/i.test(c));if(cls.length)return `${el.tagName.toLowerCase()}.${CSS.escape(cls[0])}`;const attr=[...el.attributes].find(a=>/^data-(testid|component|type|role)$/.test(a.name)&&/^[\w -]{1,60}$/.test(a.value));return attr?`${el.tagName.toLowerCase()}[${attr.name}="${attr.value}"]`:el.tagName.toLowerCase();};
    let container=target.closest("article");for(let node=target.parentElement;!container && node && !/BODY|HTML/.test(node.tagName);node=node.parentElement){const sel=selector(node);if(doc.querySelectorAll(sel).length>=2 && node.querySelector("h1,h2,h3,h4"))container=node;}
    if(!container){setMessage("Conteneur répétitif non identifié. Cliquez sur un titre d’article ou renseignez le conteneur.");return;}
    const rule=cfg.manual ?? blank;const selected=field==="url"?target.closest("a") ?? target:target;const mode=field==="url"||field==="image"?"url":field==="publishedAt"&&selected.hasAttribute("datetime")?"attribute":"text";
    setConfig({...cfg,manual:{...rule,type:"css",container:selector(container),fields:{...rule.fields,[field]:{selector:selected===container?"":selector(selected),mode,attribute:field==="image"?"src":field==="url"?"href":mode==="attribute"?"datetime":undefined}}}});setAnalysis(undefined);
  });}
  return <section className="panel"><h2>{feed?"Modifier l’extraction":"Corriger l’extraction / Créer un flux avancé"}</h2><p>Le test exécute réellement les règles. L’enregistrement des réglages ne remplace pas les articles connus : utilisez ensuite « Actualiser maintenant ».</p>
    {feed?<label>Nom<input value={title} onChange={e=>setTitle(e.target.value)}/></label>:<label>URL source<input type="url" value={url} onChange={e=>{setUrl(e.target.value);setToken("");setAnalysis(undefined);}}/></label>}
    <details open><summary>Paramètres avancés</summary><SettingsForm value={config} onChange={change}/></details>
    <label><input type="checkbox" checked={!!config.manual} onChange={e=>change({...config,manual:e.target.checked?blank:undefined})}/> Définir mes sélecteurs</label>
    {config.manual&&<><div className="settings-grid"><label>Syntaxe<select value={config.manual.type} onChange={e=>changeRule({...config.manual!,type:e.target.value as "css"|"xpath"})}><option value="css">CSS</option><option value="xpath">XPath avancé</option></select></label><label>Conteneur article<input value={config.manual.container} onChange={e=>changeRule({...config.manual!,container:e.target.value})}/></label></div><p>{total!==undefined?`${total} éléments détectés`:"Chargez la page pour tester les sélecteurs CSS en temps réel. XPath : utilisez Tester les règles. Les sélecteurs de champ sont relatifs au conteneur (XPath : .//…)."}</p>
    {fields.map(key=>{const f=config.manual!.fields[key]??{selector:"",mode:"text" as const};return <div className="rule-row" key={key}><label>{labels[key]}<input placeholder="Sélecteur relatif" value={f.selector} onChange={e=>changeRule({...config.manual!,fields:{...config.manual!.fields,[key]:{...f,selector:e.target.value}}})}/></label><select aria-label={`Mode ${labels[key]}`} value={f.mode} onChange={e=>changeRule({...config.manual!,fields:{...config.manual!.fields,[key]:{...f,mode:e.target.value as typeof f.mode}}})}>{["text","attribute","html","url"].map(m=><option key={m}>{m}</option>)}</select><input aria-label={`Attribut ${labels[key]}`} placeholder="Attribut (href, src…)" value={f.attribute??""} onChange={e=>changeRule({...config.manual!,fields:{...config.manual!.fields,[key]:{...f,attribute:e.target.value||undefined}}})}/><small>{matches[key]&&`${matches[key].count} éléments · ${matches[key].values.join(" / ")}`}</small></div>;})}</>}
    <div className="actions"><button disabled={busy||!url} onClick={()=>run("preview")}>Sélectionner sur la page / Charger l’aperçu</button><button disabled={busy||!url} onClick={()=>run("test")}>{busy?"Analyse en cours…":"Tester les règles"}</button><button disabled={busy||(!feed&&!analysis)} onClick={save}>{feed?"Enregistrer les réglages":"Créer le flux RSS"}</button></div>
    {html&&<><label>Cliquer sur : <select value={pick} onChange={e=>setPick(e.target.value as Field)}>{fields.map(f=><option key={f} value={f}>{labels[f]}</option>)}</select></label><p>Représentation sécurisée sans scripts ni ressources distantes. Un clic propose une règle ; vérifiez les correspondances avant de l’enregistrer.</p><iframe ref={iframe} title="Sélection visuelle de la page" sandbox="allow-same-origin" srcDoc={html} onLoad={connectPicker} className="visual-picker"/></>}
    {message&&<pre className="diagnostic" role="status">{message}</pre>}{analysis&&<ArticlePreview analysis={analysis}/>}
  </section>;
}
