"use client";
import { useEffect,useState } from "react";
import type { Analysis } from "@/lib/types";
import type { FeedState,RefreshLog,Proposal } from "@/lib/store";
import FavoriteArticles from "./FavoriteArticles";
import type { WatchConfig } from "@/lib/watch-types";
import { ArticlePreview } from "./ExtractionEditor";
export const when=(value?:string)=>value?new Date(value).toLocaleString("fr-FR"):"—";
export function History({logs}:{logs:RefreshLog[]}) {return <section id="history" className="panel"><h2>Historique des actualisations</h2>{!logs.length&&<p>Aucune actualisation exécutée.</p>}{logs.map(log=><details key={log.id}><summary>{when(log.startedAt)} · {log.status} · {log.method?.toUpperCase()} · {log.itemsFound} articles · {log.newItems} nouveaux · {log.durationMs!==undefined?(log.durationMs/1000).toFixed(1)+" s":"En cours"} {log.errorType}</summary>{log.errorMessage&&<p className="error">{log.errorMessage}</p>}<ol className="technical-log">{log.events.map((event,i)=><li key={i}><time>{when(event.at)}</time> · {event.message}</li>)}</ol></details>)}</section>;}
export default function FeedManager({id}:{id:string}) {
  const [data,setData]=useState<{feed:Analysis;watch:WatchConfig;state:FeedState;history:RefreshLog[];proposal?:Proposal}>();const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  async function load(){const r=await fetch(`/api/manage/${id}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message);setData(d);}
  useEffect(()=>{let mounted=true;const poll=()=>{if(mounted)void load().catch(e=>setMessage(String(e)));};poll();const timer=setInterval(poll,3000);return()=>{mounted=false;clearInterval(timer);};},[id]);
  async function action(action:string){if(action==="delete"&&!confirm("Supprimer ce flux et son historique ?"))return;setBusy(true);setMessage("");try{const r=await fetch(`/api/manage/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const result=await r.json();if(!r.ok)throw new Error(result.message);if(action==="delete"){location.href="/feeds";return;}if(result.id){location.href=`/feeds/${result.id}`;return;}setMessage(result.message);await load();}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  if(!data)return <p>{message||"Chargement du flux…"}</p>;
  const {feed,state,history,proposal,watch}=data;const running=state.status==="Actualisation en cours";
  return <><nav className="actions"><a href="#articles">Articles</a>{watch.kind==="source"&&<a href={`/feeds/${id}/edit`}>Extraction</a>}<a href={`/feeds/${id}/rules#filters`}>Filtres</a><a href={`/feeds/${id}/rules#transforms`}>Transformations</a><a href={`/feeds/${id}/history`}>Historique</a><a href="#diagnostic">Diagnostic</a><a href={`/veille/new?source=${id}`}>Créer un flux dérivé</a><a href="/favorites">Favoris</a></nav><section className="panel"><div className="settings-grid"><p><strong>Statut</strong><br/>{state.status}</p><p><strong>Méthode actuelle</strong><br/>{feed.method.toUpperCase()} · {Math.round(feed.confidence*100)} %<br/>{feed.detail}</p><p><strong>Articles connus</strong><br/>{feed.items.length} · {state.newItems} nouveaux</p><p><strong>Fréquence</strong><br/>{state.settings.refreshMinutes?`${state.settings.refreshMinutes} minutes`:"Manuel"}</p><p><strong>Dernière actualisation</strong><br/>{when(state.lastRunAt)}</p><p><strong>Prochaine actualisation</strong><br/>{when(state.nextRunAt)}</p></div><div className="actions"><button disabled={busy||running} onClick={()=>action("refresh")}>{running?"Actualisation en cours…":"Actualiser maintenant"}</button>{watch.kind==="source"&&<a href={`/feeds/${id}/edit`}>Modifier / Modifier extraction</a>}<a href={`/feeds/${id}/history`}>Historique</a><a href="#diagnostic">Diagnostic</a><button disabled={busy||running} onClick={()=>action("reanalyze")}>Réanalyser automatiquement</button><button disabled={busy||running} onClick={()=>action("duplicate")}>Dupliquer</button><button disabled={busy||running} onClick={()=>action("toggle")}>{state.enabled?"Désactiver":"Activer"}</button><button disabled={busy||running} onClick={()=>action("delete")}>Supprimer</button></div>{message&&<p role="status">{message}</p>}{history[0]?.status==="success"&&<p>{state.newItems?`${state.newItems} nouveaux articles détectés.`:"Aucun nouvel article."}</p>}</section>
  <section id="diagnostic" className="panel"><h2>Diagnostic</h2><p>Conteneur : {state.settings.manual?.container ?? "Détection automatique"} · Pagination : {state.settings.pagination?state.settings.maxPages+" pages":"page actuelle"} · Scroll : {state.settings.scroll?"activé":"désactivé"} · Timeout : {state.settings.timeoutMs/1000} s</p>{history[0]?.errorMessage&&<p className="error">{history[0].errorType} — {history[0].errorMessage}</p>}{!history.length&&<p>Lancez une actualisation pour afficher le journal technique.</p>}</section>
  {proposal&&<section className="panel"><h2>Une nouvelle méthode d’extraction a été détectée</h2><div className="settings-grid"><div><h3>Ancienne règle</h3><p>{state.settings.manual?.container??feed.detail}</p><p>Dernier résultat : {proposal.previousCount} articles · {feed.items.length} connus conservés</p></div><div><h3>Nouvelle méthode proposée</h3><p>{proposal.analysis.method.toUpperCase()} · {proposal.analysis.detail}</p><p>{proposal.analysis.items.length} articles · Correspondance des URLs : {Math.round(proposal.overlap*100)} %</p></div></div><p>Les articles connus et la nouvelle extraction sont affichés ci-dessous pour comparer titres, dates et URLs. Rien n’est adopté automatiquement.</p><ArticlePreview analysis={proposal.analysis}/><div className="actions"><button disabled={busy||running} onClick={()=>action("accept")}>Utiliser cette règle</button><button disabled={busy||running} onClick={()=>action("reject")}>Conserver l’ancienne règle</button><button disabled={busy||running} onClick={()=>action("reanalyze")}>Tester davantage</button></div></section>}
  <FavoriteArticles feed={feed}/><History logs={history.slice(0,10)}/></>;
}
