"use client";
import {useEffect,useState} from "react";
import type {Analysis,FeedItem} from "@/lib/types";
import type {FeedState} from "@/lib/store";
import type {WatchConfig} from "@/lib/watch-types";
import {when} from "./FeedManager";
interface Row {feed:Analysis;state:FeedState;watch:WatchConfig;error?:string}
export default function Library({favoritesOnly=false}:{favoritesOnly?:boolean}) {
 const [rows,setRows]=useState<Row[]>([]),[favorites,setFavorites]=useState<FeedItem[]>([]),[query,setQuery]=useState(""),[folder,setFolder]=useState(""),[tag,setTag]=useState(""),[status,setStatus]=useState(""),[favorite,setFavorite]=useState(favoritesOnly),[sort,setSort]=useState("name"),[selected,setSelected]=useState<string[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/watch",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.message);setRows(d.rows);setFavorites(d.favorites);}
 useEffect(()=>{void load().catch(e=>setMessage(String(e)));},[]);
 async function api(body:Record<string,unknown>){const r=await fetch("/api/watch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.message);return data;}
 async function action(id:string,action:string,enabled?:boolean){setMessage("");try{if(action==="favorite"){await api({id,action,enabled});await load();return;}if(action==="copy"){await navigator.clipboard.writeText(new URL(`/feed/${id}`,location.origin).href);setMessage("URL locale copiée. Pour un lecteur distant, copiez l’URL publique sur la page du flux.");return;}if(action==="delete"&&!confirm("Supprimer ce flux et son historique ?"))return;const r=await fetch(`/api/manage/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action})});const d=await r.json();if(!r.ok)throw new Error(d.message);if(d.id){location.href=`/feeds/${d.id}`;return;}if(action==="refresh"){location.href=`/feeds/${id}`;return;}await load();}catch(e){setMessage(String(e));}}
 async function articleFavorite(item:FeedItem,id:string|undefined,enabled:boolean){try{await api({action:"articleFavorite",id,url:item.url,enabled});await load();}catch(e){setMessage(String(e));}}
 async function importFile(file:File){if(file.size>1000000){setMessage("Fichier trop volumineux : maximum 1 Mo.");return;}setBusy(true);try{const data=await api({action:"import",format:/\.opml$|\.xml$/i.test(file.name)?"opml":"json",text:await file.text()});setMessage(data.message);await load();}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 const norm=(text:string)=>text.normalize("NFD").replace(/\p{M}/gu,"").toLocaleLowerCase();const q=norm(query);
 const textItem=(i:FeedItem)=>[i.title,i.description,i.url,i.sourceName,i.category,i.author].join(" ");
 const visible=rows.filter(r=>(!folder||r.watch.folder===folder)&&(!tag||r.watch.tags.includes(tag))&&(!status||r.state.status===status)&&(!favorite||r.watch.favorite)&&(!q||norm([r.feed.title,r.feed.url,...r.watch.tags,...r.feed.items.map(textItem)].join(" ")).includes(q))).sort((a,b)=>sort==="name"?a.feed.title.localeCompare(b.feed.title,"fr"):sort==="articles"?b.feed.items.length-a.feed.items.length:Date.parse(b.state.lastRunAt??b.feed.createdAt)-Date.parse(a.state.lastRunAt??a.feed.createdAt));
 const hits=query?visible.flatMap(r=>r.feed.items.filter(i=>norm(textItem(i)).includes(q)).map(item=>({item,id:r.feed.id}))).slice(0,50):[];
 const exportUrl=(format:string,scope:string)=>`/api/watch?export=${format}${scope==="selection"?`&ids=${encodeURIComponent(selected.join(","))}`:scope==="folder"?`&folder=${encodeURIComponent(folder)}`:""}`;
 return <><section className="panel"><div className="actions"><a href="/">+ Source web</a><a href="/veille/new">+ Flux thématique / agrégé</a><a href={favoritesOnly?"/feeds":"/favorites"}>{favoritesOnly?"Tous les flux":"Favoris"}</a></div><div className="settings-grid"><label>Recherche globale<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Flux, article, source, URL ou mot-clé"/></label><label>Dossier<select aria-label="Dossier" value={folder} onChange={e=>setFolder(e.target.value)}><option value="">Tous</option>{[...new Set(rows.map(r=>r.watch.folder))].filter(Boolean).sort().map(f=><option key={f}>{f}</option>)}</select></label><label>Tag<select aria-label="Tag" value={tag} onChange={e=>setTag(e.target.value)}><option value="">Tous</option>{[...new Set(rows.flatMap(r=>r.watch.tags))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Statut<select aria-label="Statut" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous</option>{[...new Set(rows.map(r=>r.state.status))].map(s=><option key={s}>{s}</option>)}</select></label><label>Tri<select aria-label="Tri" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Nom</option><option value="updated">Dernière actualisation</option><option value="articles">Nombre d’articles</option></select></label><label><input type="checkbox" checked={favorite} onChange={e=>setFavorite(e.target.checked)}/> Flux favoris uniquement</label></div>
 <details><summary>Importer / Exporter</summary><p>Import OPML : noms, URLs et dossiers. Import JSON : configuration complète et dépendances. Les articles seront téléchargés lors de l’actualisation des sources. L’import ajoute de nouveaux flux sans écraser les existants.</p><label>Importer OPML ou JSON<input disabled={busy} type="file" accept=".opml,.xml,.json" onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);e.target.value="";}}/></label><p>L’export OPML utilise l’URL HTTPS du tunnel actif ; sinon les URLs restent locales et ne fonctionnent pas dans un lecteur distant. L’export JSON est destiné à restaurer les réglages dans Source. L’export GITHUB conserve les identifiants et ajoute les noms de fichiers publics : enregistrez-le dans config/feeds.json après avoir vérifié que les noms, URLs et règles ne sont pas confidentiels.</p><div className="actions">{["opml","json","github"].map(format=><span key={format}><a download href={exportUrl(format,"all")}>Exporter tout ({format.toUpperCase()})</a>{folder&&<> · <a download href={exportUrl(format,"folder")}>Ce dossier</a></>}{selected.length>0&&<> · <a download href={exportUrl(format,"selection")}>Sélection ({selected.length})</a></>}</span>)}</div></details>
 {message&&<p role="status" className="diagnostic">{message}</p>}<p>{visible.length} flux affichés</p><div className="table-scroll"><table><thead><tr>{["Sélection","Nom / site","Type / méthode","Dossier / tags","Articles","Nouveaux","Dernière / prochaine","Statut","Actions"].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{visible.map(({feed:f,state:s,watch:w,error})=><tr key={f.id}><td><input aria-label={`Sélectionner ${f.title}`} type="checkbox" checked={selected.includes(f.id)} onChange={e=>setSelected(e.target.checked?[...selected,f.id]:selected.filter(id=>id!==f.id))}/><button className="star-button" aria-label={`${w.favorite?"Retirer des":"Ajouter aux"} favoris ${f.title}`} onClick={()=>action(f.id,"favorite",!w.favorite)}>{w.favorite?"★":"☆"}</button></td><td><a href={`/feeds/${f.id}`}>{f.title}</a><br/><small>{new URL(f.url).hostname}</small></td><td>{w.kind==="aggregate"?"Agrégé":w.kind==="derived"?"Filtré":f.method.toUpperCase()}</td><td>{w.folder||"—"}<br/>{w.tags.join(" · ")}</td><td>{f.items.length}</td><td>{s.newItems}</td><td>{when(s.lastRunAt)}<br/>{when(s.nextRunAt)}</td><td>{error??s.status}</td><td><details><summary>Actions</summary><div className="actions"><a href={`/feeds/${f.id}`}>Ouvrir</a><a href={`/feeds/${f.id}/rules`}>Filtres / Organisation</a><a href={`/veille/new?source=${f.id}`}>Créer un flux dérivé</a>{w.kind==="source"&&<a href={`/feeds/${f.id}/edit`}>Extraction</a>}<a href={`/feeds/${f.id}/history`}>Historique</a><a href={`/feeds/${f.id}#diagnostic`}>Diagnostic</a>{[["copy","Copier RSS"],["refresh",w.kind==="source"?"Actualiser":"Recalculer"],["duplicate","Dupliquer"],["toggle",s.enabled?"Désactiver":"Activer"],["delete","Supprimer"]].map(([a,t])=><button key={a} onClick={()=>action(f.id,a)}>{t}</button>)}</div></details></td></tr>)}</tbody></table></div></section>
 {query&&<section className="panel"><h2>Articles trouvés (50 premiers)</h2>{hits.map(({item,id},i)=><article className="search-result" key={id+item.url+i}><button className="star-button" aria-label={`Favori ${item.title}`} onClick={()=>articleFavorite(item,id,!favorites.some(f=>f.url===item.url))}>{favorites.some(f=>f.url===item.url)?"★":"☆"}</button><a href={item.url} target="_blank" rel="noreferrer">{item.title}</a><p>{item.sourceName} · {when(item.publishedAt)}</p><p>{item.description.slice(0,250)}</p></article>)}</section>}
 {favoritesOnly&&<section className="panel"><h2>Articles favoris</h2>{!favorites.length&&<p>Marquez une étoile dans les articles d’un flux ou les résultats de recherche.</p>}{favorites.filter(i=>!q||norm(textItem(i)).includes(q)).map(item=><article className="search-result" key={item.url}><button className="star-button" aria-label={`Retirer ${item.title}`} onClick={()=>articleFavorite(item,undefined,false)}>★</button><a href={item.url} target="_blank" rel="noreferrer">{item.title}</a><p>{item.sourceName} · {when(item.publishedAt)}</p><p>{item.description.slice(0,250)}</p></article>)}</section>}</>;
}
