"use client";
import { filterFields,operators,type Filter,type Group,type Criterion } from "@/lib/watch-types";
export const fieldLabels:Record<string,string>={title:"Titre",description:"Description",content:"Contenu disponible",url:"URL",author:"Auteur",category:"Catégorie",site:"Nom du site",date:"Date",source:"Source",titleOrDescription:"Titre OU description"};
const opLabels:Record<string,string>={contains:"contient",notContains:"ne contient pas",startsWith:"commence par",endsWith:"finit par",equals:"égal à",notEquals:"n’est pas égal à",regex:"Regex",after:"après une date",before:"avant une date",lastDays:"derniers jours"};
export const newCriterion=():Criterion=>({type:"rule",field:"titleOrDescription",operator:"contains",value:"",caseSensitive:false});
export default function RuleGroup({group,onChange,depth=0}:{group:Group;onChange:(group:Group)=>void;depth?:number}) {
 const update=(index:number,value:Filter)=>onChange({...group,children:group.children.map((c,i)=>i===index?value:c)});
 return <fieldset className="filter-group"><legend>Groupe {depth+1}</legend><label>Combiner les critères<select value={group.operator} onChange={e=>onChange({...group,operator:e.target.value as Group["operator"]})}><option value="and">ET : tous</option><option value="or">OU : au moins un</option><option value="not">NON : aucun</option></select></label>
 {!group.children.length&&<p className="muted">Aucun critère : tous les articles sont conservés.</p>}
 {group.children.map((child,index)=><div key={index} className="filter-child">{child.type==="group"?<RuleGroup group={child} onChange={g=>update(index,g)} depth={depth+1}/>:<div className="criterion"><select aria-label="Champ filtré" value={child.field} onChange={e=>update(index,{...child,field:e.target.value as Criterion["field"],operator:e.target.value==="date"?"lastDays":"contains",value:e.target.value==="date"?"7":""})}>{filterFields.map(f=><option value={f} key={f}>{fieldLabels[f]}</option>)}</select><select aria-label="Comparateur" value={child.operator} onChange={e=>update(index,{...child,operator:e.target.value as Criterion["operator"]})}>{operators.filter(op=>child.field==="date"?["after","before","lastDays"].includes(op):!["after","before","lastDays"].includes(op)).map(op=><option value={op} key={op}>{opLabels[op]}</option>)}</select><input aria-label="Valeur du critère" type={child.operator==="after"||child.operator==="before"?"date":child.operator==="lastDays"?"number":"text"} value={child.value} list={child.operator==="lastDays"?"date-periods":undefined} onChange={e=>update(index,{...child,value:e.target.value})}/><label><input type="checkbox" checked={child.caseSensitive} onChange={e=>update(index,{...child,caseSensitive:e.target.checked})}/> Respecter la casse</label></div>}<button className="small-button" onClick={()=>onChange({...group,children:group.children.filter((_,i)=>i!==index)})}>Retirer {child.type==="group"?"le groupe":"le critère"}</button></div>)}
 <div className="actions"><button className="small-button" disabled={group.children.length>=30} onClick={()=>onChange({...group,children:[...group.children,newCriterion()]})}>+ Critère</button><button className="small-button" disabled={depth>=4||group.children.length>=30} onClick={()=>onChange({...group,children:[...group.children,{type:"group",operator:"or",children:[newCriterion()]}]})}>+ Groupe</button></div><datalist id="date-periods"><option value="1">24 heures</option><option value="7">7 jours</option><option value="30">30 jours</option></datalist>
 </fieldset>;
}
