"use client";
import {useState} from "react";
import type {Analysis} from "@/lib/types";
import {watchDefaults,type WatchConfig,type Transformation,type Criterion} from "@/lib/watch-types";
import RuleGroup from "./RuleGroup";
import {ArticlePreview} from "./ExtractionEditor";
export default function WatchEditor({feed,initial,sources,creating=false}:{feed:Analysis;initial?:WatchConfig;sources:{id:string;title:string}[];creating?:boolean}) {
 const [config,setConfig]=useState(initial??{...watchDefaults(),kind:"derived",sourceIds:[feed.id]} as WatchConfig);const [title,setTitle]=useState(creating?"Nouvelle veille":feed.title);const [message,setMessage]=useState("");const [preview,setPreview]=useState<Analysis>();const [busy,setBusy]=useState(false);const [keywords,setKeywords]=useState("");const [exclusions,setExclusions]=useState("");
 const change=(value:WatchConfig)=>{setConfig(value);setPreview(undefined);};
 async function run(action:string){setBusy(true);setMessage("");try{const r=await fetch("/api/watch",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:feed.id,action,config,title,creating})});const data=await r.json();if(!r.ok)throw new Error(data.message);if(data.id){location.href=`/feeds/${data.id}`;return;}if(data.feed)setPreview(data.feed);setMessage(data.message??"Aperçu calculé sur les articles stockés, sans télécharger les sources.");}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 function thematic(){const criteria=(text:string):Criterion[]=>text.split(/\n|;/).map(s=>s.trim()).filter(Boolean).map(value=>({type:"rule",field:"titleOrDescription",operator:"contains",value,caseSensitive:false}));const included=criteria(keywords),excluded=criteria(exclusions);change({...config,filter:{type:"group",operator:"and",children:[...(included.length?[{type:"group" as const,operator:"or" as const,children:included}]:[]),...(excluded.length?[{type:"group" as const,operator:"not" as const,children:excluded}]:[])]}});}
 const transform=(index:number,value:Transformation)=>change({...config,transformations:config.transformations.map((t,i)=>i===index?value:t)});
 return <section className="panel"><h1>{creating?"Créer une veille thématique":"Filtres et transformations"}</h1><p>Les règles utilisent les articles déjà connus. Une modification met à jour le RSS sans relancer l’extraction.</p>{creating&&<label>Nom du flux<input value={title} onChange={e=>setTitle(e.target.value)}/></label>}
 <nav className="actions"><a href="#sources">Sources</a><a href="#filters">Filtres</a><a href="#transforms">Transformations</a><a href="#organization">Organisation</a></nav>
 <section id="sources"><h2>Sources</h2><label>Type de flux<select value={config.kind} onChange={e=>{const kind=e.target.value as WatchConfig["kind"];change({...config,kind,sourceIds:kind==="source"?[]:kind==="derived"?(config.sourceIds.length?[config.sourceIds[0]]:[sources.find(s=>creating||s.id!==feed.id)?.id??""]):config.sourceIds});}}>{!creating&&config.kind==="source"&&<option value="source">Source extraite</option>}<option value="derived">Flux filtré depuis une source</option><option value="aggregate">Flux agrégé / thématique</option></select></label>
 {config.kind!=="source"&&<fieldset><legend>{config.kind==="derived"?"Choisir une source":"Sources à agréger"}</legend>{sources.filter(s=>creating||s.id!==feed.id).map(s=><label key={s.id}><input type={config.kind==="derived"?"radio":"checkbox"} name="source" checked={config.sourceIds.includes(s.id)} onChange={e=>change({...config,sourceIds:config.kind==="derived"?[s.id]:e.target.checked?[...config.sourceIds,s.id]:config.sourceIds.filter(id=>id!==s.id)})}/> {s.title}</label>)}</fieldset>}
 </section><section id="filters"><h2>Filtres</h2><details><summary>Assistant de flux thématique</summary><div className="settings-grid"><label>Mots-clés (une expression par ligne, OU)<textarea value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder={'PSC\nprotection sociale complémentaire'}/></label><label>Exclusions (une expression par ligne)<textarea value={exclusions} onChange={e=>setExclusions(e.target.value)}/></label></div><button onClick={thematic}>Construire les groupes</button><p>Cette action remplace les groupes du formulaire. Ils ne sont enregistrés qu’après validation.</p></details><RuleGroup group={config.filter} onChange={filter=>change({...config,filter})}/></section>
 <section id="transforms"><h2>Transformations</h2><p>Exécutées dans l’ordre. Modèles : [PSC] {'{titre}'} ou [{'{'+'source'+'}'}] {'{titre}'}. Les Regex utilisent la syntaxe JavaScript, avec une durée bornée.</p>
 {config.transformations.map((t,index)=><div className="filter-child" key={index}><div className="criterion"><select aria-label="Champ transformé" value={t.field} onChange={e=>transform(index,{...t,field:e.target.value as Transformation["field"]})}><option value="title">Titre</option><option value="description">Description</option></select><select aria-label="Transformation" value={t.operation} onChange={e=>transform(index,{...t,operation:e.target.value as Transformation["operation"]})}>{[["template","Modèle / préfixe"],["replace","Rechercher / remplacer"],["remove","Supprimer chaîne / bloc"],["trim","Normaliser les espaces"],["truncate","Limiter la longueur"],["plain","Supprimer le HTML"],["safeHtml","Conserver le HTML propre"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input aria-label="Texte ou longueur" value={t.value} onChange={e=>transform(index,{...t,value:e.target.value})} placeholder="Texte, modèle, motif ou longueur"/><input aria-label="Remplacement" value={t.replacement} onChange={e=>transform(index,{...t,replacement:e.target.value})} placeholder="Remplacement"/></div><label><input type="checkbox" checked={t.regex} onChange={e=>transform(index,{...t,regex:e.target.checked})}/> Regex (rechercher / supprimer)</label><label><input type="checkbox" checked={t.caseSensitive} onChange={e=>transform(index,{...t,caseSensitive:e.target.checked})}/> Respecter la casse</label><button className="small-button" onClick={()=>change({...config,transformations:config.transformations.filter((_,i)=>i!==index)})}>Retirer</button></div>)}<button disabled={config.transformations.length>=30} onClick={()=>change({...config,transformations:[...config.transformations,{field:"title",operation:"template",value:"[PSC] {titre}",replacement:"",regex:false,caseSensitive:false}]})}>+ Transformation</button></section>
 <section><h2>Tri et doublons</h2><div className="settings-grid"><label>Tri<select value={config.sort} onChange={e=>change({...config,sort:e.target.value as WatchConfig["sort"]})}><option value="newest">Date de publication décroissante</option><option value="oldest">Date de publication croissante</option><option value="detected">Date de détection décroissante</option></select></label><label>Niveau de dédoublonnage<select value={config.dedup.level} onChange={e=>change({...config,dedup:{...config.dedup,level:e.target.value as WatchConfig["dedup"]["level"]}})}>{[["url","URL identique"],["title","Titre normalisé identique"],["similar","Forte similarité du titre"],["dated","Titre similaire + dates proches"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Seuil de similarité (%)<input type="number" min="50" max="100" value={config.dedup.threshold} onChange={e=>change({...config,dedup:{...config.dedup,threshold:+e.target.value}})}/></label><label>Proximité des dates (heures)<input type="number" min="1" max="8760" value={config.dedup.dateHours} onChange={e=>change({...config,dedup:{...config.dedup,dateHours:+e.target.value}})}/></label><label>Conserver<select value={config.dedup.keep} onChange={e=>change({...config,dedup:{...config.dedup,keep:e.target.value as WatchConfig["dedup"]["keep"]}})}>{[["first","Premier détecté"],["newest","Plus récent"],["both","Les deux"],["priority","Source prioritaire"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>
 {config.dedup.keep==="priority"&&<label>Priorité des sources (haut = prioritaire)<select multiple size={Math.min(8,sources.length)} value={[]} onChange={e=>{const id=e.target.value;change({...config,dedup:{...config.dedup,priorities:[...config.dedup.priorities.filter(v=>v!==id),id]}});}}>{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><p>Cliquez les sources dans l’ordre souhaité. Un nouveau clic déplace la source à la fin.</p><ol>{config.dedup.priorities.map(id=><li key={id}>{sources.find(s=>s.id===id)?.title??id}</li>)}</ol></label>}</section>
 <section id="organization"><h2>Organisation</h2><div className="settings-grid"><label>Dossier principal<input value={config.folder} placeholder="Santé / Hôpitaux" onChange={e=>change({...config,folder:e.target.value})}/></label><label>Tags (séparés par des virgules)<input value={config.tags.join(",")} onChange={e=>change({...config,tags:e.target.value.split(",")})}/></label><label><input type="checkbox" checked={config.favorite} onChange={e=>change({...config,favorite:e.target.checked})}/> Flux favori</label></div></section>
 <div className="actions"><button disabled={busy} onClick={()=>run("preview")}>{busy?"Calcul…":"Tester le filtre"}</button><button disabled={busy} onClick={()=>run(creating?"create":"save")}>{creating?"Créer le flux RSS thématique":"Enregistrer"}</button></div>{message&&<p role="status">{message}</p>}{preview&&<section className="preview"><h2>Aperçu</h2><p>Articles analysés : {preview.watchReport?.analyzed} · Conservés : {preview.watchReport?.kept} · Exclus par filtre : {preview.watchReport?.excluded} · Doublons retirés : {preview.watchReport?.duplicates.length}</p><ArticlePreview analysis={preview}/>{!!preview.watchReport?.duplicates.length&&<details><summary>Diagnostic des doublons</summary>{preview.watchReport.duplicates.slice(0,20).map((d,i)=><p key={i}>Conservé : {d.kept}<br/>Retiré : {d.removed}<br/>Similarité : {Math.round(d.score*100)} %</p>)}</details>}</section>}
 </section>;
}
